apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - host: baseline.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "baseline-helm.fullname" $ }}
            port:
              number: {{ $.Values.service.port }}

